seed: 2000

model:
  # --- General training arguments ---
  train_episodes: 1000
  # Total episodes to train
  curriculum_episodes: 0
  # Amount of curriculum episodes
  hidden_size: 256
  # network hidden size, for both actor and critic
  eval_interval: 50
  # How many training episodes to run an evaluation
  test_seeds:
    - 100
    - 125
    - 150
  # List of seeds for evaluation

  # --- Algorithm specific arguments ---
  learning_rate: !!float 1e-4
  # the learning rate of the optimizer

  reward_scale: 25.0
  # scales the reward by a factor of (1 / reward_scale)
